controller_list:
  - name: fake_scara_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_rotation
      - epaule_translation
      - epaule_rotation
      - pince_rotation
  - name: fake_scara_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - verin
      - fermeture_pince_ouverture
  - name: fake_scara_couvercle_controller
    type: $(arg fake_execution_type)
    joints:
      - stockageBoite_couvercle
      - stockageBoite_couvercle2
      - stockageBoite_couvercle3
initial:  # Define initial robot poses per group
  - group: scara_arm
    pose: home